baseURL = 'https://hannahbridgetprice.me.uk/'
languageCode = 'en-gb'
title = 'Oats & Totes'
theme = 'PaperMod'

[menu]
    [[menu.main]]
        name = 'Mains'
        url = 'categories/main-dishes/'

    [[menu.main]]
        name = 'Lunches & Sides'
        url = 'categories/side-dishes-and-lunches'

    [[menu.main]]
        name = 'Desserts'
        url = 'categories/desserts/'

    [[menu.main]]
        name = 'Search'
        url = 'search/'


[params]
    [params.homeInfoParams]
        Title = 'Oats & Totes'
        Content = 'All of my favourite vegan recipes in one place.'

    [[params.socialIcons]]
        name = 'linkedin'
        url = 'https://www.linkedin.com/in/hannah-bridget-price-098a27201/'

    [[params.socialIcons]]
        name = 'instagram'
        url = 'https://www.instagram.com/oatsandtotes/'

    [[params.socialIcons]]
        name = 'github'
        url = 'https://github.com/earthlingbridget'
    
    [params.label]
        icon = '/favicon.png'

[outputs]
home = [ "HTML", "RSS", "JSON" ]     